import React, { useState } from 'react';
import { ResearchReport } from '../../types';
import { FileSpreadsheet, Download, Copy, Check, FileText, Sparkles, Quote, Printer } from 'lucide-react';
import { CitatedPdfModal } from '../common/CitatedPdfModal';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType } from 'docx';

interface ReportGeneratorPageProps {
  report: ResearchReport;
  onGenerateNewReport: (template: string) => Promise<void>;
  isLoading: boolean;
}

export const ReportGeneratorPage: React.FC<ReportGeneratorPageProps> = ({
  report,
  onGenerateNewReport,
  isLoading
}) => {
  const [selectedTemplate, setSelectedTemplate] = useState<'literature_review' | 'executive_brief' | 'gap_analysis' | 'systematic_comparison' | 'ieee_paper'>('ieee_paper');
  const [copied, setCopied] = useState(false);
  const [activeTab, setActiveTab] = useState<'summary' | 'markdown'>('summary');
  const [isPdfModalOpen, setIsPdfModalOpen] = useState(false);

  // Editable report state
  const [editableReportTitle, setEditableReportTitle] = useState(report.title);
  const [editableExecSummary, setEditableExecSummary] = useState(report.executiveSummary);
  const [editableSections, setEditableSections] = useState(report.sections);
  const [isInlineEditing, setIsInlineEditing] = useState(false);

  // Sync if report prop changes
  React.useEffect(() => {
    setEditableReportTitle(report.title);
    setEditableExecSummary(report.executiveSummary);
    setEditableSections(report.sections);
  }, [report]);

  const handleSectionHeadingChange = (index: number, newHeading: string) => {
    const updated = [...editableSections];
    updated[index] = { ...updated[index], heading: newHeading };
    setEditableSections(updated);
  };

  const handleSectionContentChange = (index: number, newContent: string) => {
    const updated = [...editableSections];
    updated[index] = { ...updated[index], content: newContent };
    setEditableSections(updated);
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(report.markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([report.markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.title.replace(/\s+/g, '_')}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadJSON = () => {
    const blob = new Blob([JSON.stringify(report, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${editableReportTitle.replace(/\s+/g, '_')}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadHTML = () => {
    const htmlContent = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${editableReportTitle}</title>
  <style>
    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #1e293b; max-width: 900px; margin: 40px auto; padding: 0 20px; }
    h1 { color: #0f172a; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
    h2 { color: #1e293b; margin-top: 28px; }
    .summary { background: #f8fafc; border-left: 4px solid #4f46e5; padding: 16px; border-radius: 4px; margin-bottom: 24px; }
    .section { margin-bottom: 20px; }
    footer { margin-top: 40px; font-size: 0.85em; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 12px; }
  </style>
</head>
<body>
  <h1>${editableReportTitle}</h1>
  <div class="summary">
    <strong>Executive Summary:</strong>
    <p>${editableExecSummary}</p>
  </div>
  ${editableSections.map((sec, idx) => `
    <div class="section">
      <h2>${idx + 1}. ${sec.heading}</h2>
      <p>${sec.content}</p>
    </div>
  `).join('')}
  <footer>
    Generated by Atherion Research Operating System • Confidential Report
  </footer>
</body>
</html>`;
    const blob = new Blob([htmlContent], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${editableReportTitle.replace(/\s+/g, '_')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleDownloadDOCX = async () => {
    try {
      const docChildren: any[] = [];

      docChildren.push(
        new Paragraph({
          text: editableReportTitle,
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 300 }
        })
      );

      docChildren.push(
        new Paragraph({
          children: [
            new TextRun({ text: "Executive Summary: ", bold: true }),
            new TextRun({ text: editableExecSummary })
          ],
          spacing: { after: 300 }
        })
      );

      editableSections.forEach((sec, idx) => {
        docChildren.push(
          new Paragraph({
            text: `${idx + 1}. ${sec.heading}`,
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 150 }
          })
        );

        docChildren.push(
          new Paragraph({
            children: [new TextRun({ text: sec.content })],
            spacing: { after: 200 }
          })
        );
      });

      const doc = new Document({
        sections: [{
          properties: {},
          children: docChildren
        }]
      });

      const blob = await Packer.toBlob(doc);
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `${editableReportTitle.replace(/\s+/g, '_')}.docx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (err) {
      console.error("Failed to generate DOCX:", err);
    }
  };

  const handlePrintPDF = () => {
    setIsPdfModalOpen(true);
  };

  return (
    <div className="p-6 max-w-7xl mx-auto space-y-8">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-white font-display flex items-center gap-2.5">
            <FileSpreadsheet className="w-6 h-6 text-indigo-400" />
            <span>Executive Report Generator</span>
          </h1>
          <p className="text-xs text-slate-400 mt-1">
            Synthesize publication-ready literature reviews, executive briefs, and citation-backed academic reports.
          </p>
        </div>

        {/* Download Buttons */}
        <div className="flex items-center gap-2">
          <button
            onClick={handleCopyMarkdown}
            className="px-3 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-semibold text-slate-300 flex items-center gap-1.5 transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>Copy MD</span>
          </button>

          <button
            onClick={handleDownloadMarkdown}
            className="px-3 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-semibold text-slate-300 flex items-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5 text-indigo-400" />
            <span>Download .MD</span>
          </button>

          <button
            onClick={handleDownloadJSON}
            className="px-3 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-semibold text-slate-300 flex items-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5 text-violet-400" />
            <span>Export JSON</span>
          </button>

          <button
            onClick={handleDownloadHTML}
            className="px-3 py-2 rounded-xl bg-slate-900 hover:bg-slate-800 border border-slate-800 text-xs font-semibold text-slate-300 flex items-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5 text-cyan-400" />
            <span>Export HTML</span>
          </button>

          <button
            onClick={handleDownloadDOCX}
            className="px-3.5 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-md transition-all"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Export .DOCX</span>
          </button>

          <button
            onClick={handlePrintPDF}
            className="px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-semibold flex items-center gap-1.5 shadow-lg shadow-indigo-600/20 transition-all"
          >
            <Printer className="w-3.5 h-3.5" />
            <span>Print / PDF</span>
          </button>
        </div>
      </div>

      {/* Template Selector Bar */}
      <div className="p-4 rounded-2xl bg-slate-900 border border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4">
        <div className="flex items-center gap-3 w-full sm:w-auto">
          <span className="text-xs font-bold text-slate-300 uppercase tracking-wider shrink-0">Report Template:</span>
          <select
            value={selectedTemplate}
            onChange={(e) => setSelectedTemplate(e.target.value as any)}
            className="bg-slate-950 border border-slate-800 text-white text-xs rounded-xl px-3 py-2 focus:outline-none w-full sm:w-auto"
          >
            <option value="ieee_paper">IEEE Conference Paper Format (IEEE Transactions)</option>
            <option value="literature_review">Executive Literature Review</option>
            <option value="executive_brief">1-Page C-Suite Research Brief</option>
            <option value="gap_analysis">Research Gap & Opportunity Report</option>
            <option value="systematic_comparison">Systematic Paper Comparison</option>
          </select>
        </div>

        <button
          onClick={() => onGenerateNewReport(selectedTemplate)}
          disabled={isLoading}
          className="w-full sm:w-auto px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white text-xs font-semibold flex items-center justify-center gap-2 shadow-md"
        >
          <Sparkles className="w-4 h-4" />
          <span>Generate Fresh Report</span>
        </button>
      </div>

      {/* Main Report View Card */}
      <div className="rounded-2xl bg-slate-900 border border-slate-800 p-6 sm:p-8 space-y-6 shadow-2xl">
        {/* View Tabs */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between border-b border-slate-800 pb-4 gap-3">
          <div className="flex-1">
            {isInlineEditing ? (
              <input
                type="text"
                value={editableReportTitle}
                onChange={(e) => setEditableReportTitle(e.target.value)}
                className="text-xl font-bold text-white bg-slate-950 border border-slate-700 rounded-lg px-3 py-1.5 w-full focus:outline-none focus:border-indigo-500"
              />
            ) : (
              <h2 className="text-xl font-bold text-white font-display">{editableReportTitle}</h2>
            )}
            <span className="text-xs text-slate-400 mt-0.5 block">Generated on {report.generatedAt} • 100% Grounded</span>
          </div>

          <div className="flex items-center gap-2 flex-wrap">
            <button
              onClick={() => setIsInlineEditing(!isInlineEditing)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold border transition-all ${
                isInlineEditing
                  ? 'bg-amber-500/20 text-amber-300 border-amber-500/40'
                  : 'bg-slate-800 text-slate-300 border-slate-700 hover:bg-slate-700'
              }`}
            >
              {isInlineEditing ? 'Save & Lock Edits' : 'Edit Sections'}
            </button>

            <div className="flex items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
              <button
                onClick={() => setActiveTab('summary')}
                className={`px-3 py-1.5 rounded-lg font-semibold transition-colors ${
                  activeTab === 'summary' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Structured Layout
              </button>
              <button
                onClick={() => setActiveTab('markdown')}
                className={`px-3 py-1.5 rounded-lg font-semibold transition-colors ${
                  activeTab === 'markdown' ? 'bg-indigo-600 text-white' : 'text-slate-400 hover:text-slate-200'
                }`}
              >
                Raw Markdown
              </button>
            </div>
          </div>
        </div>

        {activeTab === 'summary' ? (
          <div className="space-y-6 text-xs text-slate-300 leading-relaxed">
            {/* Executive Summary Box */}
            <div className="p-5 rounded-2xl bg-indigo-950/30 border border-indigo-500/30 space-y-2">
              <span className="text-xs font-bold text-indigo-300 uppercase tracking-wider block">Executive Summary</span>
              {isInlineEditing ? (
                <textarea
                  value={editableExecSummary}
                  onChange={(e) => setEditableExecSummary(e.target.value)}
                  rows={3}
                  className="w-full bg-slate-950 border border-slate-700 rounded-lg p-2.5 text-slate-200 text-xs focus:outline-none focus:border-indigo-500"
                />
              ) : (
                <p className="text-slate-200">{editableExecSummary}</p>
              )}
            </div>

            {/* Sections */}
            <div className="space-y-6 pt-2">
              {editableSections.map((sec, idx) => (
                <div key={idx} className="space-y-3 p-5 rounded-xl bg-slate-950 border border-slate-800/80">
                  {isInlineEditing ? (
                    <input
                      type="text"
                      value={sec.heading}
                      onChange={(e) => handleSectionHeadingChange(idx, e.target.value)}
                      className="text-base font-bold text-white font-display bg-slate-900 border border-slate-700 rounded-lg px-3 py-1.5 w-full focus:outline-none focus:border-indigo-500"
                    />
                  ) : (
                    <h3 className="text-base font-bold text-white font-display">{sec.heading}</h3>
                  )}

                  {isInlineEditing ? (
                    <textarea
                      value={sec.content}
                      onChange={(e) => handleSectionContentChange(idx, e.target.value)}
                      rows={5}
                      className="w-full bg-slate-900 border border-slate-700 rounded-lg p-3 text-slate-200 text-xs font-mono leading-relaxed focus:outline-none focus:border-indigo-500"
                    />
                  ) : (
                    <p className="text-slate-300 leading-relaxed">{sec.content}</p>
                  )}

                  {sec.citations && sec.citations.length > 0 && (
                    <div className="pt-2 flex flex-wrap gap-2 border-t border-slate-800/60">
                      {sec.citations.map((cit, cIdx) => (
                        <span key={cIdx} className="px-2.5 py-1 rounded-lg bg-slate-900 border border-slate-800 text-[11px] text-indigo-300 flex items-center gap-1">
                          <Quote className="w-3 h-3 text-indigo-400" />
                          <span>{cit.documentName} (p.{cit.pageNumber})</span>
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        ) : (
          <pre className="p-6 rounded-2xl bg-slate-950 border border-slate-800 font-mono text-xs text-slate-200 overflow-x-auto whitespace-pre-wrap leading-relaxed">
            {editableExecSummary + "\n\n" + editableSections.map(s => `## ${s.heading}\n${s.content}`).join("\n\n")}
          </pre>
        )}
      </div>

      <CitatedPdfModal
        isOpen={isPdfModalOpen}
        onClose={() => setIsPdfModalOpen(false)}
        title={editableReportTitle}
        groundingScore={98.5}
        customContent={editableExecSummary + "\n\n" + editableSections.map(s => `## ${s.heading}\n${s.content}`).join("\n\n")}
        citations={editableSections.flatMap(s => s.citations || [])}
      />
    </div>
  );
};
